### ISSUE TITLE
Workflow on PyPi

### ISSUE THREAD

**Issue by gelzinyte** [libAtoms/workflow#187]
Make wfl available on pypi for easy pip installation.  What should the package name be?

**Comment by simonwengert** [comment]
I can take this one.

1. Repeating your question from above: Which package name? `wfl`?
2. From a quick research on how to achieve this, I see there are github-action workflows to publish on PyPi. Do we want such a pipeline to make `wfl` available on PyPi?

**Comment by simonwengert** [comment]
Seems like the `install_requires` that point to github projects cause problems for the upload to PyPi. 

```
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/
                 Invalid value for requires_dist. Error: Can't have direct dependency: 'expyre-wfl @ https://github.com/libAtoms/ExPyRe/tarball/main'                                                                                                                                               
```
I'm not sure, if it's even possible to add them as valid dependencies for PyPi uploads (see e.g. https://github.com/pypa/pip/issues/6301).
Probably, we'll need a workaround for that, e.g. telling users to install these dependencies manually...

**Comment by bernstei** [comment]
What about just putting expyre-wfl on pypi also, then requiring the pypi version rather than the github version?

**Comment by simonwengert** [comment]
> What about just putting expyre-wfl on pypi also, then requiring the pypi version rather than the github version?

Putting `expyre-wfl` and `universalSOAP` on PyPi should solve this, too, in my view.

**Comment by simonwengert** [comment]
@noambernstein Since I am not active on these two projects, will you put them on PyPi?

**Comment by simonwengert** [comment]
> given an example here that I can convert for those packages

You mean an example for how to put the packages on PyPi?

**Comment by bernstei** [comment]
Yes - presumably we want to do it for every tagged release  with a CI action.

Actually, in some ways it'd be easier for me (internal paperwork-wise) if someone other than me can do it.  @gelzinyte I know you passed this one off on @simonwengert , but would you be able to do it for the other two?

**Comment by gelzinyte** [comment]
Sure, I might as well do all three. But let me come back to this after the initial submission..

**Comment by simonwengert** [comment]
Having a CI action would be great. I haven't been uploading a package on PyPi before. Thus, so far I don't have a script that I could post. In general, I think it's just the two commands (related to `build` and `twine` as explained here https://packaging.python.org/en/latest/tutorials/packaging-projects/ for the Test PyPi, so `python3 -m build` and `python3 -m twine upload --repository testpypi dist/*`).

A CI action would then probably look similar to the one in `matscipy` https://github.com/libAtoms/matscipy/blob/master/.github/workflows/build-wheels.yml (at the bottom of the file).

**Comment by simonwengert** [comment]
```
# This workflow will upload a Python Package using Twine when a release is created

name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
          python-version: ${{ matrix.python-version }}
        
    - name: Check tag
      id: check-tag
      run: |
        if [[ ${{ github.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo "match=true" >> $GITHUB_OUTPUT              
        fi
      shell: bash
      
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade build
        python3 -m pip install --upgrade twine
      shell: bash
        
    - name: Build package
      run: python -m build
      shell: bash
      
    - name: Deploy package
      if: steps.check-tag.outputs.match == 'true'
      run: |
        python3 -m twine upload --repository testpypi dist/*
      env:
        TWINE_USERNAME: '__token__'
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      shell: bash
```
For another repo of mine, I successfully implemented this for the CI. I could make a test if it, in principle, will also work for `wfl` (uncommenting the github-dependencies for this test for a moment) or if we need some adjustments. This requires permissions to set github-secrets which I currently do not have, though.

Note that:

1. The script above uploads to `testpypi`. For the production pipeline, remove ` --repository testpypi`.
2. For releases it expects the tagging of the form `v[0-9]+\.[0-9]+\.[0-9]+`
